apiVersion: v1
kind: Service
metadata:
    name: posts-service-nodeport
spec:
    type: NodePort
    ports:
        - port: 4000
          targetPort: 4000
          nodePort: 31515
    selector:
        app: posts