apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: posts
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - name: posts
                  image: hars1014/posts

---
apiVersion: v1
kind: Service
metadata:
    name: posts-service
spec:
    type: ClusterIP
    ports:
        - port: 4000
          targetPort: 4000
    selector:
        app: posts