apiVersion: v1
kind: Service
metadata:
    name: comments-service-nodeport
spec:
    type: NodePort
    selector:
        app: comments
    ports:
        - port: 4001
          targetPort: 4001
          nodePort: 31516