apiVersion: apps/v1
kind: Deployment
metadata:
    name: event-bus-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: event-bus
    template:
        metadata:
            labels:
                app: event-bus
        spec:
            containers:
                - name: event-bus
                  image: hars1014/event-bus

---
apiVersion: v1
kind: Service
metadata:
    name: event-bus-service
spec:
    type: ClusterIP
    selector:
        app: event-bus
    ports:
        - port: 4002
          targetPort: 4002


