apiVersion: apps/v1
kind: Deployment
metadata:
    name: query-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: query
    template:
        metadata:
            labels:
                app: query
        spec:
            containers:
                - name: query
                  image: hars1014/query

---
apiVersion: v1
kind: Service
metadata:
    name: query-service
spec:
    type: ClusterIP
    selector:
        app: query
    ports:
        - port: 4005
          targetPort: 4005