apiVersion: v1
kind: Service
metadata:
    name: query-service-nodeport
spec:
    type: NodePort
    selector:
        app: query
    ports:
        - port: 4005
          targetPort: 4005
          nodePort: 31517